---
- name: Reth - create group
  ansible.builtin.group:
    name: "{{ reth_group }}"
    state: present

- name: Reth - user configuration
  ansible.builtin.user:
    name: "{{ reth_user }}"
    groups: "{{ reth_group }}"
    append: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Reth - create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ reth_user }}"
    group: "{{ reth_group }}"
  with_items:
    - "{{ reth_dir_base }}"
    - "{{ reth_dir_data }}"
    - "{{ reth_dir_config }}"
    - "{{ reth_dir_log }}"

- name: Reth - install required apt packages
  ansible.builtin.apt:
    name:
      - curl
      - openssl
      - gcc
    update_cache: true
