---
- name: prepare
  hosts: all
  tasks:
    - name: install default packages
      apt:
        name:
          - net-tools
          - curl
          - openssl
          - nano
        update_cache: true
